### Ejercicio

In [1]:
import numpy as np

Paso 1: Crear Arrays con Datos de Ventas

Usa la librería numpy para crear los siguientes arrays:
meses: un array con los nombres de los meses del año.
ventas_A, ventas_B, ventas_C: arrays que representan las ventas mensuales de tres productos diferentes.

In [2]:
months = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto',
                    'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])
product_A = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
product_B = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
product_C = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])

Paso 2: Estadísticas Básicas

Calcula la media y la suma de ventas para los productos A, B y C usando las funciones de NumPy.
Imprime estos valores en el formato siguiente:
Media de ventas Producto A: <valor>
Suma de ventas Producto A: <valor>
Repite para los productos B y C.

In [10]:
median_A = np.mean(product_A)
median_B = np.mean(product_B)
median_C = np.mean(product_C)

print("Media de ventas Producto A: ", median_A, "Suma de ventas Producto A: ", np.sum(product_A))
print("Media de ventas Producto B: ", median_B, "Suma de ventas Producto B: ", np.sum(product_B))
print("Media de ventas Producto C: ", median_C, "Suma de ventas Producto C: ", np.sum(product_C))

Media de ventas Producto A:  229.16666666666666 Suma de ventas Producto A:  2750
Media de ventas Producto B:  257.5 Suma de ventas Producto B:  3090
Media de ventas Producto C:  310.0 Suma de ventas Producto C:  3720


Paso 3: Manipulación y Análisis de Datos

Total de ventas por mes: Suma las ventas de los tres productos para cada mes.
Promedio de ventas por producto: Calcula el promedio de ventas por producto.
Mes con mayor y menor ventas: Identifica qué mes tuvo el total de ventas más alto y cuál el más bajo usando las funciones np.argmax y np.argmin.

In [8]:
Total_per_months = product_A + product_B + product_C
print("Total de ventas por mes: ", Total_per_months)

mean_A = np.mean(product_A) #mean devuelve la media de un array
mean_B = np.mean(product_B) 
mean_C = np.mean(product_C)


print("Media de ventas Producto A: ", mean_A)
print("Media de ventas Producto B: ", mean_B)
print("Media de ventas Producto C: ", mean_C)

max_sales_month = np.argmax(Total_per_months)   #argmax devuelve el índice del valor máximo
min_sales_month = np.argmin(Total_per_months)   #argmin devuelve el índice del valor mínimo

print("Mes con mayor venta: ", months[max_sales_month], "con un total de: ", Total_per_months[max_sales_month])
print("Mes con menor venta: ", months[min_sales_month], "con un total de: ", Total_per_months[min_sales_month])


Total de ventas por mes:  [ 530  630  720  810  770  770  740  780  860  910  990 1050]
Media de ventas Producto A:  229.16666666666666
Media de ventas Producto B:  257.5
Media de ventas Producto C:  310.0
Mes con mayor venta:  Diciembre con un total de:  1050
Mes con menor venta:  Enero con un total de:  530


Paso 4: Operaciones Avanzadas con NumPy

Reshape y Transposición:

Crea una matriz 2D con las ventas de los tres productos y transforma su forma (reshape) a un array tridimensional con dimensiones (3, 4, 3).
Transpone la matriz de ventas para que las filas se conviertan en columnas.
Invertir arrays: Invierte las ventas de cada producto en orden de meses.
Aplanar la matriz: Convierte la matriz de ventas a un array unidimensional.

In [23]:
bd_ABC = np.array([product_A, product_B, product_C]) #crea un array de 3x12
reshaped_A = bd_ABC.reshape(3,4,3) #reshape cambia la forma a un array tridimensional de 3x4x3
print('Matriz de ventas tridimensional')
print(reshaped_A)
print('-----------------------------------------------------------------------------')
reshaped_T = reshaped_A.T #transpone el array tridimensional
print('Matriz de ventas tridimensional transpuesta')
print(reshaped_T)
print('-----------------------------------------------------------------------------')
print('matriz de ventas bidimensional')
print(bd_ABC)
print('-----------------------------------------------------------------------------')
bd_ABC_T = bd_ABC.T #transpone el array de 3x12
print('matriz de ventas transpuesta')
print(bd_ABC_T)
print('-----------------------------------------------------------------------------')
inverse_A = product_A[::-1] #invierte el array
inverse_B = product_B[::-1]
inverse_C = product_C[::-1]
print('Ventas invertidas Producto A: ', inverse_A)
print('Ventas invertidas Producto B: ', inverse_B)
print('Ventas invertidas Producto C: ', inverse_C)
print('-----------------------------------------------------------------------------')
sales_flattened = bd_ABC.flatten() #convierte el array de 3x12 a un array de 1x36
print('Ventas aplanadas')
print(sales_flattened)

Matriz de ventas tridimensional
[[[150 200 250]
  [300 220 210]
  [180 190 230]
  [240 280 300]]

 [[180 210 230]
  [250 270 260]
  [240 250 270]
  [290 310 330]]

 [[200 220 240]
  [260 280 300]
  [320 340 360]
  [380 400 420]]]
-----------------------------------------------------------------------------
Matriz de ventas tridimensional transpuesta
[[[150 180 200]
  [300 250 260]
  [180 240 320]
  [240 290 380]]

 [[200 210 220]
  [220 270 280]
  [190 250 340]
  [280 310 400]]

 [[250 230 240]
  [210 260 300]
  [230 270 360]
  [300 330 420]]]
-----------------------------------------------------------------------------
matriz de ventas bidimensional
[[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]
-----------------------------------------------------------------------------
matriz de ventas transpuesta
[[150 180 200]
 [200 210 220]
 [250 230 240]
 [300 250 260]
 [220 270 280]
 [210

Paso 5: Análisis de Elementos Únicos

Utiliza np.unique para encontrar los elementos únicos en los datos de ventas y cuenta cuántas veces aparece cada uno.

In [27]:
unique_A, countA = np.unique(product_A, return_counts=True) #unique devuelve los valores únicos de un array
unique_B, countB = np.unique(product_B, return_counts=True)
unique_C, countC = np.unique(product_C, return_counts=True)

print('Valores únicos Producto A: ', unique_A)
print('conteo de valores unicos en A: ', countA)
print('Valores únicos Producto B: ', unique_B)
print('conteo de valores unicos en B: ', countB)
print('Valores únicos Producto C: ', unique_C)
print('conteo de valores unicos en C: ', countC)

Valores únicos Producto A:  [150 180 190 200 210 220 230 240 250 280 300]
conteo de valores unicos en A:  [1 1 1 1 1 1 1 1 1 1 2]
Valores únicos Producto B:  [180 210 230 240 250 260 270 290 310 330]
conteo de valores unicos en B:  [1 1 1 1 2 1 2 1 1 1]
Valores únicos Producto C:  [200 220 240 260 280 300 320 340 360 380 400 420]
conteo de valores unicos en C:  [1 1 1 1 1 1 1 1 1 1 1 1]


Paso 6: Indexación y Slicing

Ventas del primer trimestre: Extrae las ventas de los tres primeros meses del año.
Indexación booleana: Selecciona los meses donde el total de ventas de los tres productos supere los 800.
Selección avanzada: Usa una lista de índices para seleccionar las ventas de los meses pares (o selecciona los meses a tu elección) y muestra esas ventas en una nueva matriz.

In [29]:
Total_per_months = product_A + product_B + product_C
print('Ventas del primer trimestre: ', Total_per_months[0:3])
index = Total_per_months>800
print('Meses con ventas mayores a 800: ', Total_per_months[index])

idx = []

Ventas del primer trimestre:  [530 630 720]
Meses con ventas mayores a 800:  [ 810  860  910  990 1050]
