### Array Transformation

### Transpose Array

In [1]:
import numpy as np

In [2]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
transposed_matrix = matrix.T
print(matrix)
print('---------------------------')
print(transposed_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------------------
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Reshape

In [4]:
array = np.arange(1,13) # 1D array from 1 to 12, 13 not included. 12 elements
reshaped_array = array.reshape(3,4) # needs to be the same size as the original array (3*4=12)
print(array)
print('---------------------------------------------')
print(reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
---------------------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Reverse

In [5]:
reversed_array = array[::-1] # reverse the array
print(array)
print('---------------------------------------------')
print(reversed_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
---------------------------------------------
[12 11 10  9  8  7  6  5  4  3  2  1]


### Flattening

Convert a multidimensional array to a unidimensional array.

In [6]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
flattened_matrix = matrix.flatten() # flatten the matrix
print(matrix)
print('---------------------------------------------')  
print(flattened_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------------------------------------
[1 2 3 4 5 6 7 8 9]
