### Broadcasting

In [1]:
import numpy as np

In [2]:
prices = np.array([100,200,300])
discount = np.array([0.9])
discount_prices = prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [4]:
prices = np.random.randint(100,500,size=(3,3))  # 3x3 matrix
discount = np.array([10,20,30])
discount_prices = prices + discount # broadcasting
print(prices)
print("discount prices:")
print(discount_prices)

[[151 372 441]
 [130 472 484]
 [477 196 375]]
discount prices:
[[161 392 471]
 [140 492 514]
 [487 216 405]]


In [6]:
array = np.array([1,2,3,4,5,6])
print(np.all(array > 0))    # True if all elements are True

True


In [8]:
print(np.any(array > 0))    # True if any element is True

True


### Matrix Concatenations

In [9]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated = np.concatenate((array_a, array_b)) # [1 2 3 4 5 6]: array_a + array_b
print(concatenated)

[1 2 3 4 5 6]


### Stacking

In [10]:
v_stacked = np.vstack((array_a, array_b)) # [[1 2 3] [4 5 6]]: vertical stack
print(v_stacked)

[[1 2 3]
 [4 5 6]]


In [11]:
h_stacked = np.hstack((array_a, array_b)) # [1 2 3 4 5 6]: horizontal stack
print(h_stacked)

[1 2 3 4 5 6]


### Splitting

In [12]:
array_c = np.arange(1,10)
array_split = np.split(array_c, 3) # [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
print(array_c)
print("-------------------------")
print(array_split)

[1 2 3 4 5 6 7 8 9]
----------------
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
