### Calculos Matriciales

In [1]:
import numpy as np

In [3]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [5]:
#Suma
sum = A + B
print(A)
print('------------------')
print(B)
print('------------------')
print(sum)

[[1 2]
 [3 4]]
------------------
[[5 6]
 [7 8]]
------------------
[[ 6  8]
 [10 12]]


In [6]:
#Resta
rest = A - B
print(A)
print('------------------') 
print(B)
print('------------------')
print(rest)


[[1 2]
 [3 4]]
------------------
[[5 6]
 [7 8]]
------------------
[[-4 -4]
 [-4 -4]]


In [7]:
#Multiplicacion (producto punto)
mult = np.dot(A,B)
print(A)
print('------------------')
print(B)
print('------------------')
print(mult)

[[1 2]
 [3 4]]
------------------
[[5 6]
 [7 8]]
------------------
[[19 22]
 [43 50]]


In [8]:
mult = A * B #(elemento por elemento)
print(A)
print('------------------')
print(B)
print('------------------')
print(mult)

[[1 2]
 [3 4]]
------------------
[[5 6]
 [7 8]]
------------------
[[ 5 12]
 [21 32]]


In [12]:
#Determinante
det_A = round(np.linalg.det(A),2)
inv_A = np.linalg.inv(A)
print(A)
print('------------------')
print(det_A)
print('------------------')
print(inv_A)

[[1 2]
 [3 4]]
------------------
-2.0
------------------
[[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
#Resolver Ax = B
B = np.array([9,11])
x = np.linalg.solve(A,B)
print(A)
print('------------------')
print(B)
print('------------------')
print(x)

[[1 2]
 [3 4]]
------------------
[ 9 11]
------------------
[-7.  8.]
