In [1]:
import numpy as np

Acceder a elementos específicos:
Crea un arreglo de 10 números y accede al cuarto y penúltimo elemento usando índices positivos y negativos.

In [5]:
array = np.arange(1,10)
print(array)
print("The 4th element is: ",array[3])     # 4th element
print("The second last element is: ",array[-2])    # 2nd last element    

[1 2 3 4 5 6 7 8 9]
The 4th element is:  4
The second last element is:  8


Slicing de arreglos:
Dado un arreglo de números del 1 al 20, extrae los elementos entre las posiciones 3 y 7, y luego los elementos de las últimas 5 posiciones.

In [10]:
array2 = np.arange(1,21,1)
print(array2)
print(array2[2:7])     # 4th to 8th element
print(array2[-5:])   # 5th last to last element

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[3 4 5 6 7]
[16 17 18 19 20]


Indexing con booleanos:
Crea un arreglo de números aleatorios entre 0 y 100. Usa una expresión booleana para acceder solo a los números mayores a 50.

In [13]:
rnd_array = np.random.randint(0,100,10)
print(rnd_array)
bool_array = rnd_array > 50
print(bool_array)

[15 16 56 45 37 67 12 16 99 64]
[False False  True False False  True False False  True  True]


Indexación con múltiples índices:
Dado un arreglo de 8 elementos, crea una lista de índices para acceder a los elementos en las posiciones 1, 4, y 6.

In [17]:
array3 = np.arange(0,8,1)
print(array3)
index = [1,4,6]
print(array3[index])

[0 1 2 3 4 5 6 7]
[1 4 6]


Matrices bidimensionales:
Genera una matriz 4x4 de números aleatorios entre 10 y 50, y accede a la submatriz de 2x2 ubicada en la esquina inferior derecha.

In [19]:
array4 = np.random.randint(10, 51, size=(4, 4))
print(array4)
print(array4[-2:,-2:])   # last 2 rows and last 2 columns

[[24 10 28 40]
 [14 19 24 45]
 [34 13 44 33]
 [49 31 26 48]]
[[44 33]
 [26 48]]
