### Indexacion y Slicing

In [1]:
import numpy as np

In [3]:
array = np.array([10,20,30,40,50])
print(array[1])     # second element 20
print(array[-1])    # last element 50

20
50


In [4]:
print(array[1:4])   # 20, 30, 40

[20 30 40]


In [5]:
print(array[1:7])  # 20, 30, 40, 50

[20 30 40 50]


In [6]:
print(array[-1:-7]) # empty array because the start index is greater than the end index

[]


### Boolean Index

In [9]:
bool_index = array > 25
print(bool_index) # [False, False, True, True, True]
print(type(bool_index)) # bool

[False False  True  True  True]
<class 'numpy.ndarray'>


In [10]:
#array = np.array([10,20,30,40,50])
index = [2,3,4]
print(array[index]) # 30, 40, 50

[30 40 50]


In [16]:
array = np.random.randint(1,10,size = (3,3))
print(array)
print(array[0,1])   # row 1 column 2

[[6 9 5]
 [9 2 4]
 [5 1 1]]
9


In [18]:
print(array[:2,:2]) # first two rows and first two columns of the array

[[6 9]
 [9 2]]
