### Arrays en Numpy

In [1]:
import numpy as np

In [2]:
# Escalar: es un número real, un número entero, un número flotante, un número complejo
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [4]:
#Vector fila
vector = np.array([30,29,35,31,33,36,42])
print(type(vector))
print(vector)

<class 'numpy.ndarray'>
[30 29 35 31 33 36 42]


In [5]:
# Matriz de 3x3
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(type(matrix))
print(matrix)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
tensor = np.array([[[1,2],
                     [3,4],
                     [5,6],
                     [7,8]]])
print(type(tensor))
print(tensor)

<class 'numpy.ndarray'>
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [7]:
# Crear un array de 10 elementos
array_range = np.arange(10)
print(array_range)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
#Matriz de identidad
eye_matrix = np.eye(6)
print(eye_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [11]:
#Matriz diagonal
diag = np.diag([1,2,3,4,5])
print(diag)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [12]:
#Crear un array de 10 elementos con valores entre 0 y 1
random = np.random.random((2,3))
print(random)

[[0.08653265 0.71412547 0.01979406]
 [0.06207519 0.23488461 0.07456792]]
